pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		gradlePluginPortal()
		mavenCentral()
	}
	includeBuild 'enigma-llm-evaluation/gradle-plugin'
}

include 'enigma'
include 'enigma-swing'
include 'enigma-server'
include 'enigma-cli'
include 'enigma-llm-plugin'
include 'enigma-llm-evaluation'
include 'enigma-llm-bridge'
